module.exports = {
  BORDER_LINE_WIDTH: 5,
  BORDER_STROKE_COLOR: "white",
  RENDER_WIDTH_DISTANCE: 1500,
  RENDER_HEIGHT_DISTANCE: 800,
  RAF_RUNNING: false,

  PELLET_COLOR: "red",
  VIRUS_COLOR: "gray",
  VIRUS_STROKE_COLOR: "white"
}